import { z } from 'zod';
import { paginatedResponseSchema, paginationQuerySchema } from './common';
import { userEmailSchema, userNameSchema, userPhoneSchema } from './user-fields';

/** Account statuses an administrator can set. */
export const staffStatusSchema = z.enum(['ACTIVE', 'INACTIVE']);

/** Every stored account status (`SUSPENDED` exists in the DB but isn't managed by this feature). */
export const userStatusSchema = z.enum(['ACTIVE', 'INACTIVE', 'SUSPENDED']);

export const staffRoleSchema = z
  .object({
    id: z.string().uuid(),
    name: z.string().min(1),
  })
  .strict();

export const staffAccountSchema = z
  .object({
    id: z.string().uuid(),
    name: z.string(),
    email: z.string().email(),
    phone: z.string().nullable(),
    status: userStatusSchema,
    role: staffRoleSchema,
    createdAt: z.string().datetime(),
  })
  .strict();

export const staffListQuerySchema = paginationQuerySchema.extend({
  search: z
    .string()
    .trim()
    .max(100, 'Search must be 100 characters or fewer')
    .optional()
    .describe('Case-insensitive match on name or email'),
  status: staffStatusSchema.optional(),
});

export const staffListResponseSchema = paginatedResponseSchema(staffAccountSchema);

/** Body for creating and for editing a staff account. The password is generated by the API. */
const staffDetailsSchema = z
  .object({
    name: userNameSchema,
    email: userEmailSchema,
    phone: userPhoneSchema,
    roleId: z.string().uuid('Select a role'),
  })
  .strict();

export const createStaffRequestSchema = staffDetailsSchema;
export const updateStaffRequestSchema = staffDetailsSchema;

export const createStaffResponseSchema = z
  .object({
    account: staffAccountSchema,
    temporaryPassword: z
      .string()
      .min(1)
      .describe('Generated password; returned only once, share it with the employee'),
  })
  .strict();

export const updateStaffStatusRequestSchema = z
  .object({
    status: staffStatusSchema,
  })
  .strict();

export const staffRolesResponseSchema = z.array(staffRoleSchema);

export type StaffStatus = z.infer<typeof staffStatusSchema>;
export type UserStatus = z.infer<typeof userStatusSchema>;
export type StaffRole = z.infer<typeof staffRoleSchema>;
export type StaffAccount = z.infer<typeof staffAccountSchema>;
export type StaffListQuery = z.infer<typeof staffListQuerySchema>;
export type StaffListResponse = z.infer<typeof staffListResponseSchema>;
export type CreateStaffRequest = z.infer<typeof createStaffRequestSchema>;
export type CreateStaffResponse = z.infer<typeof createStaffResponseSchema>;
export type UpdateStaffRequest = z.infer<typeof updateStaffRequestSchema>;
export type UpdateStaffStatusRequest = z.infer<typeof updateStaffStatusRequestSchema>;
export type StaffRolesResponse = z.infer<typeof staffRolesResponseSchema>;
